services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: t3
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - t3-db:/var/lib/postgresql/data

  api:
    build:
      context: ./src/T3.Api
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__Postgres: "Host=db;Port=5432;Database=t3;Username=postgres;Password=postgres"
      TransactionOptions__StrictIdempotency: "false"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  t3-db:
